# Generated by Django 5.1.2 on 2025-08-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('codmoneda', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descrip', models.CharField(max_length=30)),
                ('cotiz', models.DecimalField(decimal_places=5, max_digits=15)),
                ('signoc', models.CharField(max_length=3)),
            ],
        ),
    ]
