# Generated by Django 5.2.5 on 2025-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.CharField(max_length=14, unique=True, verbose_name='Código')),
                ('descrip', models.CharField(max_length=80, verbose_name='Descripción')),
                ('precosto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Costo')),
            ],
        ),
    ]
