# Generated by Django 5.2.5 on 2025-08-09 22:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alicuota',
            fields=[
                ('ncodalic', models.IntegerField(choices=[(1, 'NO GRAVADO'), (2, 'EXENTO'), (3, '0%'), (4, '10.5%'), (5, '21%'), (6, '27%'), (8, '5%'), (9, '2.5%')], primary_key=True, serialize=False, verbose_name='Código')),
                ('descrip', models.CharField(max_length=50, verbose_name='Descripción')),
                ('nporc', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje')),
            ],
            options={
                'verbose_name': 'Alicuota',
                'verbose_name_plural': 'Alicuotas',
                'ordering': ['ncodalic'],
            },
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['descrip'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AddField(
            model_name='articulo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='costoiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo con IVA'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='margen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Margen (%)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='preventa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ncodalic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='articulos.alicuota', verbose_name='Código de alícuota'),
        ),
    ]
