# Generated by Django 5.1.2 on 2025-08-10 05:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alicuota_alter_articulo_options_articulo_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alicuota',
            options={'ordering': ['ncodalic'], 'verbose_name': 'Alícuota IVA'},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='activo',
        ),
        migrations.AddField(
            model_name='articulo',
            name='alic',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, null=True, verbose_name='% Alícuota'),
        ),
        migrations.AlterField(
            model_name='alicuota',
            name='ncodalic',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alicuota',
            name='nporc',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='costoiva',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Costo con IVA'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='margen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Margen %'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ncodalic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.alicuota', verbose_name='Código Alícuota'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precosto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Costo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='preventa',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Precio Venta'),
        ),
    ]
