# Generated by Django 5.1.2 on 2025-08-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_alicuota_options_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='prefinal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Precio Final'),
        ),
    ]
