# Generated by Django 5.1.2 on 2025-08-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_articulo_prefinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='prefinal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Precio Final (con IVA)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='preventa',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Precio Venta (sin IVA)'),
        ),
    ]
