# Generated by Django 5.1.2 on 2025-08-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_alter_articulo_prefinal_alter_articulo_preventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='costoiva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Costo con IVA'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='prefinal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Precio Final (con IVA)'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='preventa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Precio Venta (sin IVA)'),
        ),
    ]
