# Generated by Django 5.1.2 on 2025-08-14 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_alter_articulo_costoiva_alter_articulo_prefinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codart',
            field=models.CharField(help_text='14 caracteres, se completa con ceros a la izquierda.', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras mayúsculas y números.', regex='^[A-Z0-9]+$')], verbose_name='Código'),
        ),
    ]
