# Generated by Django 5.1.2 on 2025-08-15 03:45

import articulos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_alter_articulo_codart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
            bases=(articulos.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rubros',
                'ordering': ['nombre'],
            },
            bases=(articulos.models.UpperCaseMixin, models.Model),
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articulos.marca'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articulos.rubro'),
        ),
    ]
