# Generated by Django 5.1.2 on 2025-08-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_marca_rubro_articulo_marca_articulo_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='modo_calculo',
            field=models.CharField(choices=[('C', 'Costo → Final'), ('F', 'Final → Costo')], default='C', max_length=1),
        ),
    ]
