# Generated by Django 5.1.2 on 2025-08-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_articulo_modo_calculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='prefinal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Precio Final (con IVA)'),
        ),
    ]
