# Generated by Django 5.1.2 on 2025-08-15 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0011_alter_articulo_prefinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='prefinal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Final (con IVA)'),
        ),
    ]
