# Generated by Django 5.1.2 on 2025-08-16 04:13

import articulos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0012_alter_articulo_prefinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=14)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='articulos.rubro')),
            ],
            options={
                'db_table': 'subrubro',
                'ordering': ['nombre'],
                'unique_together': {('rubro', 'nombre')},
            },
            bases=(articulos.models.UpperCaseMixin, models.Model),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subrubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articulos.subrubro'),
        ),
    ]
