# Generated by Django 5.1.2 on 2025-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0013_subrubro_articulo_subrubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecultmod',
            field=models.DateField(blank=True, null=True),
        ),
    ]
