# Generated by Django 5.1.2 on 2025-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0014_articulo_fecultmod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1)),
            ],
        ),
    ]
