# Generated by Django 5.1.2 on 2025-08-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0015_parametrosistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosistema',
            name='clave',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
