# Generated by Django 5.1.2 on 2025-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0016_alter_parametrosistema_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unimed',
            field=models.CharField(choices=[('UN', 'UN'), ('KG', 'KG'), ('TN', 'TN'), ('MT', 'MT'), ('LT', 'LT')], default='UN', max_length=2),
        ),
    ]
