# Generated by Django 5.1.2 on 2025-08-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0017_articulo_cantidad_articulo_unimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='bajostock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11, verbose_name='Stock mínimo para alerta'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='codprovee',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código de proveedor'),
        ),
    ]
