# Generated by Django 5.1.2 on 2025-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0018_articulo_bajostock_articulo_codprovee'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Ubicación'),
        ),
    ]
