# Generated by Django 5.1.2 on 2025-08-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0019_articulo_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='deposito',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Depósito'),
        ),
    ]
