# Generated by Django 5.1.2 on 2025-08-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0020_articulo_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='obs',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observaciones'),
        ),
    ]
