# Generated by Django 5.1.2 on 2025-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0021_articulo_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
