# Generated by Django 5.1.2 on 2025-08-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0022_alter_articulo_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='activo',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1),
        ),
    ]
