# Generated by Django 5.1.2 on 2025-08-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0023_articulo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='activo',
            field=models.CharField(choices=[('True', 'Sí'), ('False', 'No')], max_length=5),
        ),
    ]
