# Generated by Django 5.1.2 on 2025-08-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0024_alter_articulo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='activo',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1),
        ),
    ]
