# Generated by Django 5.1.2 on 2025-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0026_alter_articulo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='prodela',
            field=models.IntegerField(blank=True, choices=[(1, 'Prod. elaborado'), (2, 'Prod. elaborado intermedio'), (3, 'Insumo')], null=True),
        ),
    ]
