# Generated by Django 5.1.2 on 2025-08-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0027_articulo_prodela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='costoiva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Costo con IVA'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='preventa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Precio Venta (sin IVA)'),
        ),
    ]
