# Generated by Django 5.1.2 on 2025-08-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0028_alter_articulo_costoiva_alter_articulo_preventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='tipopeso',
            field=models.IntegerField(blank=True, choices=[(1, 'Pesable por precio'), (2, 'Pesable por peso'), (3, 'No aplica')], null=True),
        ),
    ]
