# Generated by Django 5.1.2 on 2025-08-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0029_articulo_tipopeso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='modo_calculo',
            field=models.CharField(choices=[('C', 'Costo → Final'), ('F', 'Final → Costo')], default='C', max_length=1, verbose_name='Modo de cálculo'),
        ),
    ]
