# Generated by Django 5.1.2 on 2025-08-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0030_alter_articulo_modo_calculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cotiz',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Cotización'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ctome',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Prec. Costo de M.Ext.'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='finme',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Prec. Final de M.Ext.'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='vtame',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Prec. Venta de M.Ext.'),
        ),
    ]
