# Generated by Django 5.1.2 on 2025-08-28 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0031_articulo_cotiz_articulo_ctome_articulo_finme_and_more'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codmoneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monedas.moneda', verbose_name='Moneda'),
        ),
    ]
