# Generated by Django 5.1.2 on 2025-08-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0032_articulo_codmoneda'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codmoneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monedas.moneda', verbose_name='Moneda:'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cotiz',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Cotización:'),
        ),
    ]
