# Generated by Django 5.1.2 on 2025-09-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0033_alter_articulo_codmoneda_alter_articulo_cotiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codmoneda',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda'),
        ),
    ]
