# Generated by Django 5.1.2 on 2025-09-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0034_alter_articulo_codmoneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('codlista', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código de lista')),
                ('nomlista', models.CharField(max_length=20, verbose_name='Nombre de lista')),
                ('dtolista', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Descuento (%)')),
                ('reclista', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Recargo (%)')),
            ],
        ),
    ]
